modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="sorcerer_secrets"
version="1.0.0"
displayName="Sorcerer Secrets"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Ian13"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sorcerer_secrets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.sorcerer_secrets]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sorcerer_secrets]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sorcerer_secrets]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sorcerer_secrets]]
    modId="ldlib_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sorcerer_secrets]]
    modId="photon_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration